# Site settings
name: FlySnow的博客
email: 389528688@qq.com
author: FlySnow
url: https://flyonsnow.github.io/
resume_site: https://flyonsnow.github.io/
github: https://github.com/luoyan35714/
baseurl: ""
description: 每天记录一点
meta_description: meta描述
motto: motto
banner: banner

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: flyonsnow
rouge: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 65640a36324eb9144666384b7b1bdfb7

FB:
  comments :
    provider : provider
    duoshuo:
        short_name : flysnow
    disqus :
        short_name : flysnowd
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light